# -*- coding: utf-8 -*-
"""SMS spam detector

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_dIJyvabqZUeoLWi7HRwBwP_-B42YYw
"""

import os
import sys
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

class RobustSpamDetector:
    def __init__(self):
        # TF-IDF + multinomial naive bayes pipeline optimized for short texts
        self.model = Pipeline([
            ('tfidf', TfidfVectorizer(
                ngram_range=(1, 2),
                max_df=0.95,
                min_df=2,
                stop_words='english',
                sublinear_tf=True
            )),
            ('clf', MultinomialNB(alpha=0.1))
        ])
        self.is_trained = False

    def load_data(self, filepath: str) -> pd.DataFrame:
        """Safely loads CSV with encoding fallbacks and auto-cleans columns."""
        if not os.path.exists(filepath):
            raise FileNotFoundError(f"Dataset file '{filepath}' not found.")

        #robust encoding fallback mechanism
        df = None
        for enc in ['utf-8', 'latin-1', 'iso-8859-1', 'cp1252']:
            try:
                df = pd.read_csv(filepath, encoding=enc)
                break
            except (UnicodeDecodeError, pd.errors.ParserError):
                continue

        if df is None or df.empty:
            raise ValueError("Failed to load dataset: File is empty or improperly formatted.")

        #handle typical UCI SMS dataset schemas or auto-detect label/text columns
        df = df.iloc[:, :2]
        df.columns = ['label', 'text']
        df.dropna(subset=['label', 'text'], inplace=True)

        #standardize labels (0 for ham, 1 for spam)
        df['label'] = df['label'].astype(str).str.lower().str.strip()
        df['label'] = df['label'].map({'ham': 0, 'spam': 1, '0': 0, '1': 1})
        df.dropna(subset=['label'], inplace=True)

        return df

    def train(self, filepath: str) -> dict:
        """Trains the model and returns performance metrics."""
        df = self.load_data(filepath)

        X_train, X_test, y_train, y_test = train_test_split(
            df['text'], df['label'], test_size=0.2, random_state=42, stratify=df['label']
        )

        self.model.fit(X_train, y_train)
        self.is_trained = True

        preds = self.model.predict(X_test)
        return classification_report(y_test, preds, target_names=['Ham', 'Spam'], output_dict=True)

    def predict(self, text: str) -> dict:
        """Safe prediction endpoint handling invalid/edge-case inputs gracefully."""
        if not self.is_trained:
            raise RuntimeError("Model is not trained yet. Call train() first.")

        #guard clause for empty or non-string inputs
        if not isinstance(text, str) or not text.strip():
            return {"label": "Ham", "confidence": 1.0, "is_spam": False}

        probs = self.model.predict_proba([text])[0]
        spam_prob = probs[1]
        is_spam = bool(spam_prob > 0.5)

        return {
            "label": "Spam" if is_spam else "Ham",
            "confidence": round(float(probs[1] if is_spam else probs[0]), 4),
            "is_spam": is_spam
        }

if __name__ == "__main__":
    dataset_path = "spam.csv"

    detector = RobustSpamDetector()
    try:
        metrics = detector.train(dataset_path)
        print(f"Model trained successfully. Accuracy: {metrics['accuracy'] * 100:.2f}%\n")

        #live Test
        samples = [
            "WINNER!! As a valued network customer you have been selected to receive a £900 prize reward!",
            "Hey mate, are we still meeting for lunch today?",
            "", #Edge case: empty input
            12345 #Edge case: invalid input type
        ]

        for msg in samples:
            res = detector.predict(str(msg) if not isinstance(msg, str) else msg)
            print(f"Input : '{msg}'\nResult: {res['label']} ({res['confidence']*100:.1f}% confidence)\n")

    except Exception as e:
        print(f"Execution failed: {e}", file=sys.stderr)